### PR TITLE
Fix: cleaning up leaks

### PR DESCRIPTION
**Pull request by iaurg**
Looking and trying to fix leaks

### CODE REVIEW

**Comment by vcwild** [comment]
Avoid making this MR too long (don't clear too much leaks at once). Also try rebasing it before merge.

**Comment by vcwild** [comment]
I have removed the leak fixes from `to_linked_list` because they break the unit tests.

**Comment by vcwild** [comment]
Fixed them errors and brought back the implementation to this branch

**Comment by iaurg** [comment]
I'll end this branch and merge it following your advice.

**Review by vcwild — APPROVED** [review]
I will trust the CI on this one.
I am looking for ways to improve our test coverage. Maybe in the next cleanup we would be better.

**Pull request merged**
