### PR TITLE
Check and validate

### PR DESCRIPTION
**Pull request by iaurg**
Checking invalid inputs, tests and invalid commands

- [x] fix tab press two times on empty shell to suppress return (I've tested on various minishells and all return the same "error")
- [x] fix error on absolute path:
```bash
italo@xxyyxx 42-minishell ~ $ cd /bin/
italo@xxyyxx bin ~ $ echo $
JS ERROR;JS LOG
italo@xxyyxx bin ~ $ 
```
- [x] signal CTRL + C after press with a command wrote in line above, returns the command...

### CODE REVIEW

**Comment by iaurg** [comment]
If we press `tab` two times our shell returns something like `ls` command...

**Comment by vcwild** [comment]
Marking `signal CTRL + C after press with a command wrote in line above, returns the command...` as complete.

**Comment by iaurg** [comment]
Some inconsistency on echo:

bash:
```bash
export TEST=LOL
echo $TEST$TEST$TEST=lol$TEST

returns

LOLLOLLOL=lolLOL
```

In our minishell returns empty

**Comment by iaurg** [comment]
Remember to update with all flags needed by PDF:
```
CFLAGS	=	-Wall -Wextra -g -O0 -Og
```

**Comment by iaurg** [comment]
Remember to test everything on workspace

**Comment by iaurg** [comment]
export without params

**Pull request closed without merging**
